version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - cd client
      - npm install
  build:
    commands:
      - npm run build
      - cd ..
  post_build:
    commands:
      - mkdir dist
      - mv client/build/* dist/
      - rm -rf client/build client/node_modules
artifacts:
  files:
    - dist/**/*
